<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Quantitative Analysis 2 - Answers to Assignment 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="styles-lecture-slides.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Quantitative Analysis 2</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../primer.html"> 
<span class="menu-text">Primers</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-setup" id="toc-assignment-setup" class="nav-link active" data-scroll-target="#assignment-setup">Assignment Setup</a></li>
  <li><a href="#question-1." id="toc-question-1." class="nav-link" data-scroll-target="#question-1.">Question 1.</a></li>
  <li><a href="#question-2." id="toc-question-2." class="nav-link" data-scroll-target="#question-2.">Question 2.</a></li>
  <li><a href="#question-3." id="toc-question-3." class="nav-link" data-scroll-target="#question-3.">Question 3.</a></li>
  <li><a href="#question-4." id="toc-question-4." class="nav-link" data-scroll-target="#question-4.">Question 4.</a></li>
  <li><a href="#question-5." id="toc-question-5." class="nav-link" data-scroll-target="#question-5.">Question 5.</a></li>
  <li><a href="#question-6." id="toc-question-6." class="nav-link" data-scroll-target="#question-6.">Question 6.</a></li>
  <li><a href="#question-7." id="toc-question-7." class="nav-link" data-scroll-target="#question-7.">Question 7.</a></li>
  <li><a href="#question-8." id="toc-question-8." class="nav-link" data-scroll-target="#question-8.">Question 8.</a></li>
  <li><a href="#question-9." id="toc-question-9." class="nav-link" data-scroll-target="#question-9.">Question 9.</a>
  <ul class="collapse">
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation">Model Interpretation</a></li>
  </ul></li>
  <li><a href="#question-10." id="toc-question-10." class="nav-link" data-scroll-target="#question-10.">Question 10.</a></li>
  <li><a href="#question-11." id="toc-question-11." class="nav-link" data-scroll-target="#question-11.">Question 11.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Answers to Assignment 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="assignment-setup" class="level2">
<h2 class="anchored" data-anchor-id="assignment-setup">Assignment Setup</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required R packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the data from the class site</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data_ai <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"https://alopilato88.github.io/quantitative-analysis-1/assignments/01-assignment-data.csv"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View our data frame </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk above tells R to do three, broad tasks:</p>
<ol type="1">
<li>Load the packages we need for the code in the code chunks below using the <code>library</code> function (e.g.&nbsp;<code>library(tibble)</code>)</li>
<li>Read a .csv file using its URL using the <code>read_csv</code> function and save the .csv file in an object named <code>data_ai</code></li>
<li>Use the <code>head</code> function to print out the first 6 rows of our new object: <code>data_ai</code> (<code>head(data_ai)</code>)</li>
</ol>
<p>We told R to use a function to accomplish those three tasks. A function is a set of code that does one specific thing. For example, <code>read_csv</code> is a function that only reads .csv files. It does nothing else.</p>
<p>Next, a package such as <code>readr</code> is a collection of functions that all share a similar goal. The package <code>readr</code> contains different functions such as <code>read_csv</code>, <code>read_file</code>, and <code>write_csv</code>, which are all functions that can be used to read or write different kinds of files.</p>
</section>
<section id="question-1." class="level2">
<h2 class="anchored" data-anchor-id="question-1.">Question 1.</h2>
<div class="cell" data-lablel="question-1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. What is the sample size of your dataset (hint: It's the number of rows)? </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(data_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 500</code></pre>
</div>
</div>
<p>The sample size of our data is the number of observations in our dataset. This is equivalent to the number of rows in our dataset—one row for each observation. So we can use the R function <code>nrow</code> to tell us the number of row. In this case there are 500 rows in our dataset, which means our sample size is 500.</p>
</section>
<section id="question-2." class="level2">
<h2 class="anchored" data-anchor-id="question-2.">Question 2.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. How many variables are in your dataset (hint: It's the number of columns)? </span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(data_ai)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>In general, we will store our data in a .csv file where each column is a different variable. We can use the R function <code>ncol</code> to count the number of columns in our dataset. In our dataset, there are 4 columns, so we have 4 variables in our dataset.</p>
</section>
<section id="question-3." class="level2">
<h2 class="anchored" data-anchor-id="question-3.">Question 3.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. What is the mean and standard deviation of perceived_ease_use?</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_ai<span class="sc">$</span>perceived_ease_use) <span class="co"># mean() is a function that calculates the mean of a rando variable.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.078</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_ai<span class="sc">$</span>perceived_ease_use) <span class="co"># sd() is a function that calculates the standard deviation of a random variable.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.661758</code></pre>
</div>
</div>
<p>When you start R and RStudio, a handful of packages are loaded automatically. These packages make a lot of different functions immediately available to you. Two such functions are <code>mean</code> and <code>sd</code>.</p>
<p>The function <code>mean</code> only needs one argument—something that the use inputs—to work: a numeric R object otherwise known as a collection of numbers. <code>mean</code> then returns the mean value for the provided numeric object. In our class, the only numeric objects we will be providing to <code>mean</code> are the quantitative variables from our dataset. So to get the mean of <code>perceived_ease_use</code>, we use it as the argument in <code>mean</code>: <code>mean(data_ai$perceived_ease_use)</code>, which returns 4.078.</p>
<p>The <code>$</code> symbol used in the <code>mean</code> function tells the <code>mean</code> function to “look for” the variable <code>perceived_ease_use</code> in the dataset <code>data_ai</code>. If we did not include <code>data_ai$</code> before <code>perceived_ease_use</code>, then the mean function would not where to find <code>perceived_ease_use</code> and the function would return an error message.</p>
<p>Similarly, to calculate the standard deviation of <code>perceived_ease_use</code>, we can use the preloaded R function: <code>sd</code>. Like <code>mean</code>, <code>sd</code> only requires one numeric object as an argument and it returns the standard deviation of the numeric values stored in the object. In our assignment, our numeric objects will almost always be the quantitative varialbes in our dataset. So to get the standard deviation of <code>perceived_ease_use</code>, we use <code>perceived_ease_use</code> as the argument in <code>sd</code>: <code>sd(data_ai$perceived_ease_use)</code>, which returns 1.6617578.</p>
<p>Again we have to use the <code>$</code> to tell <code>sd</code> to find <code>perceived_ease_use</code> in our dataset <code>data_ai</code>.</p>
</section>
<section id="question-4." class="level2">
<h2 class="anchored" data-anchor-id="question-4.">Question 4.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. What is the mean and standard deviation for perceived_useful?</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_ai<span class="sc">$</span>perceived_useful)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.76</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_ai<span class="sc">$</span>perceived_useful)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.755153</code></pre>
</div>
</div>
<p>Just like question 3, we can use the <code>mean</code> function to calculate the mean of <code>perceived_useful</code> and the <code>sd</code> function to calculate its standard deviation. Again we have to tell R where to find the variable by using <code>data_ai$</code>.</p>
</section>
<section id="question-5." class="level2">
<h2 class="anchored" data-anchor-id="question-5.">Question 5.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. What is the mean and standard deviation for behavioral_intention?</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_ai<span class="sc">$</span>behavioral_intention)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.314</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_ai<span class="sc">$</span>behavioral_intention)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.563423</code></pre>
</div>
</div>
<p>Just like the previous two questions, we can use the <code>mean</code> function to calculate the mean of <code>behvioral_intention</code> and the <code>sd</code> function to calculate its standard deviation. Again we have to tell R where to find the variable by using <code>data_ai$</code>.</p>
</section>
<section id="question-6." class="level2">
<h2 class="anchored" data-anchor-id="question-6.">Question 6.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6a. What is the correlation between perceived_useful and perceived_ease_of_use? </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># cor() is a function that calculates the correlation between two random variables</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The cor() function requires two arguments: an x variable and a y variable.</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Below we tell R the x variable = data$perceived_useful and y variable = data_ai$perceived_ease_use.</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># You can read the $ operator as go into the data frame: data_ai and select the variable to the right of the $ sign.</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># data_ai$perceived_useful means go into data_ai and select the column perceived_useful</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> data_ai<span class="sc">$</span>perceived_useful, <span class="at">y =</span> data_ai<span class="sc">$</span>perceived_ease_use) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5423654</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6b. In your own words, write out an interpretation of the correlation you calculated in 6a. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To determine the correlation between two or more variables, we can use the preloaded R function: <code>cor</code>. For this homework, we only need to provide <code>cor</code> with two arguments, which are the variables we are interested in calculating a correlation coefficient for: <code>perceived_useful</code> and <code>perceived_ease_use</code>.</p>
<p><code>cor(x = data_ai$perceived_useful, y = data_ai$perceived_ease_use)</code> will go into our dataset, <code>data_ai</code>, and use the formula for the correlation coefficient to caluclate the correlation between <code>perceived_useful</code> and <code>perceived_ease_use</code>.</p>
<p>We will get the same correlation coefficient if we switch the order of our variables in the <code>cor</code> function: <code>cor(x = data_ai$perceived_ease_use, y = data_ai$perceived_useful)</code> as the correlation is symmetric. This means that the correlation between <code>perceived_ease_use</code> and <code>perceived_useful</code> is identical to the correlation between <code>perceived_useful</code> and <code>perceived_ease_use</code>.</p>
<p>As for the interpretation of the correlation, we can interpret it as:</p>
<p>In our dataset, the correlation between <code>percieved_useful</code> and <code>perceived_ease_use</code> is 0.5423654. Because the correlation is positive, we know that values of <code>percieved_ease_use</code> above the mean occur with values of <code>perceived_useful</code> that are above its mean. Similary the size of the correlation coefficient tells us that the two variables are moderately related to one another.</p>
</section>
<section id="question-7." class="level2">
<h2 class="anchored" data-anchor-id="question-7.">Question 7.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7a. What is the correlation between perceived_useful and behavioral_intention? </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> data_ai<span class="sc">$</span>perceived_useful, <span class="at">y =</span> data_ai<span class="sc">$</span>behavioral_intention) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3795281</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 7b. In your own words, write out an interpretation of the correlation you calculated in 7a. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again we can use the <code>cor</code> function. We determine that the correlation between <code>perceived_useful</code> and <code>behavioral_intention</code> is 0.3795281, which means that <code>perceived_useful</code> and <code>behavioral_intention</code> are positively and moderately correlated to one another. High values of <code>perceived_useful</code> will tend to occur with high values of <code>behavioral_intention</code>, on average.</p>
</section>
<section id="question-8." class="level2">
<h2 class="anchored" data-anchor-id="question-8.">Question 8.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 8a. What is the correlation between perceived_ease_use and behavioral_intention? </span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> data_ai<span class="sc">$</span>perceived_ease_use, <span class="at">y =</span> data_ai<span class="sc">$</span>behavioral_intention) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.412486</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 8b. In your own words, write out an interpretation of the correlation you calculated in 8a. </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again we can use the <code>cor</code> function. We determine that the correlation between <code>perceived_ease_use</code> and <code>behavioral_intention</code> is 0.412486, which means that <code>perceived_ease_use</code> and <code>behavioral_intention</code> are positively and moderately correlated to one another. High values of <code>perceived_ease_use</code> will tend to occur with high values of <code>behavioral_intention</code>, on average.</p>
</section>
<section id="question-9." class="level2">
<h2 class="anchored" data-anchor-id="question-9.">Question 9.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9a. Estimate a simple regression model that uses perceived_ease_use to predict behavioral_intention.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The lm() function used below fits a linear regression model. The lm() code translated to the following</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># regression model: behvioral_intention = B0 + B1*perceived_ease_use. </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># In general the structure of the lm() function will look like lm(outcome_variable ~ predictor_variable, data = your_data)</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># In R, everyhing to the left of the ~ sign is an outcome variable and everything to the right is a predictor variable.</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(behavioral_intention <span class="sc">~</span> perceived_ease_use, <span class="at">data =</span> data_ai)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 9b. Print out the results of your regression model and write out an interpretation of the effect of perceived_ease_use on</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">#     behavioral_intentions.</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = behavioral_intention ~ perceived_ease_use, data = data_ai)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6718 -1.0599 -0.0599  0.9401  3.4924 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         2.73142    0.16910   16.15   &lt;2e-16 ***
perceived_ease_use  0.38808    0.03841   10.11   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.426 on 498 degrees of freedom
Multiple R-squared:  0.1701,    Adjusted R-squared:  0.1685 
F-statistic: 102.1 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 9c. What is the R-squared value for model_1? Write out an interpretation of the R-squared.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To estimate a linear regression model in R, we will use the <code>lm</code> function. The <code>lm</code> function is automatically made available to us when we start R and RStudio, so we do not need to tell R to load it.</p>
<p><code>lm</code> requires two main arguments: the <code>lm</code> regression formula and the dataset that contains the predictor and outcome variables for the regression model.</p>
<p>First, the <code>lm</code> formula will always look like <code>outcome_variable_name ~ predictor_variable_name_1</code>, which we can read as estimate a linear regression model where the outcome variable is <code>outcome_variable_name</code> and the predictor variable is <code>predictor_variable_name_1</code>. In general, any variable to the left of <code>~</code> is treated as an outcome variable by <code>lm</code> and any variable to the right of <code>lm</code> is treated as a predictor variable.</p>
<p>Next, the <code>lm</code> function needs to know to where to find the dataset that contains our outcome and predictor variables. We can tell <code>lm</code> where to find our dataset by providing it with its second argument: <code>data = data_ai</code>. Now <code>lm</code> knows that <code>data_ai</code> contains the outcome and predictor variables used in the <code>lm</code> formula.</p>
<p>Now that we have provide <code>lm</code> with its two necessary arguments, we can estimate it and save it in an object we call <code>model_1</code>. This is all happening in the line of code: <code>model_1 &lt;- lm(behavioral_intention ~ perceived_ease_use, data = data_ai</code>. <code>lm</code> is estimating a regression model where <code>behavioral_intention</code> is the outcome variable and <code>perceived_ease_use</code> is the predictor variable, both of which it knows to find in <code>data_ai</code>. Then it is storing the results of that model in an object (think of it like a box) called <code>model_1</code>.</p>
<p>We know R is storing the results of the model into an object named <code>model_1</code> because of this part of the code: <code>model_1 &lt;-</code>. The <code>&lt;-</code> is called the assignment operator and it creates an object named <code>model_1</code> and <strong>assigns</strong> it the results of <code>lm(behavioral_intention ~ perceived_ease_use, data = data_ai</code>.</p>
<section id="model-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="model-interpretation">Model Interpretation</h3>
<p>Now that we have estimated our model, we can use the function <code>summary</code> to display the detailed results of our model. You should see from the results above that <code>summary</code> provides the coefficient estimates (<code>Estimate</code>), there standard errors (<code>Std. Error</code>), and a p-value (<code>Pr(&gt;|t|)</code>) along with more results like the <code>R-squared</code> value.</p>
<p>We can interpret the results as follows. When comparing two groups who differ by one unit on their response to <code>perceived_ease_use</code>, the average response to <code>behavioral_intetions</code> for the group with the higher response to <code>perceived_ease_use</code> will be 0.39 units higher than the group with the lower response.</p>
<p>We could also say: For every one unit increase in an individual’s perceptions of how easy it is to use the AI tool (<code>perceived_ease_use</code>), we will see their intentions to use the AI tool increase by 0.39. I find that this interpretation is easier to understand when compared to the group comparison interpretation, but it is less accurate.</p>
<p>The <code>R-squared</code> value in our model is 0.1701447, which means that 17% of the variance in <code>behavioral_intention</code> can be explained by <code>perceived_ease_use</code>.</p>
</section>
</section>
<section id="question-10." class="level2">
<h2 class="anchored" data-anchor-id="question-10.">Question 10.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 10a. Estimate a simple regression model that uses perceived_useful to predict behavioral_intention. Name the model: model_2.</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(behavioral_intention <span class="sc">~</span> perceived_useful, <span class="at">data =</span> data_ai)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 10b. Print out the results of your regression model and write out an interpretation of the effect of perceived_useful on</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#     behavioral_intentions.</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = behavioral_intention ~ perceived_useful, data = data_ai)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0713 -1.0571 -0.0571  0.9429  3.6191 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       2.70479    0.18733  14.439   &lt;2e-16 ***
perceived_useful  0.33807    0.03693   9.154   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.448 on 498 degrees of freedom
Multiple R-squared:  0.144, Adjusted R-squared:  0.1423 
F-statistic:  83.8 on 1 and 498 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 10c. What is the R-squared value for model_2? Write out an interpretation of the R-squared.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The steps used to answer this question are identical to those we used in question 9.</p>
<p>We can interpret the results as follows. When comparing two groups who differ by one unit on their response to <code>perceived_useful</code>, the average response to <code>behavioral_intetions</code> for the group with the higher response to <code>perceived_useful</code> will be 0.34 units higher than the group with the lower response.</p>
<p>We could also say: For every one unit increase in an individual’s perceptions of how useful the AI tool is (<code>perceived_useful</code>), we will see their intentions to use the AI tool increase by 0.34.</p>
<p>The <code>R-squared</code> value in our model is 0.1440416, which means that 14% of the variance in <code>behavioral_intention</code> can be explained by <code>perceived_useful</code>.</p>
</section>
<section id="question-11." class="level2">
<h2 class="anchored" data-anchor-id="question-11.">Question 11.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 11a. Estimate a multiple regression model that uses perceived_useful and perceived_ease_use to predict behavioral_intention.</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(behavioral_intention <span class="sc">~</span> perceived_ease_use <span class="sc">+</span> perceived_useful, <span class="at">data =</span> data_ai)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 11b. Print out the results of your multiple regression model and write out an interpretation of both partial regression </span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="co">#      coefficients.</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 11c. What is the R-squared value for model_3? Write out an interpretation of the R-squared.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The steps used to answer this question are identical to those we used in questions 9 and 10. The only difference is that instead of estimating a model with one predictor variable, we are estimating a model with two predictor variables: <code>perceived_ease_use + perceived_useful</code>. To add more predictor variables to our model, we just write: <code>+ predictor_variable_name_1 + predictor_variable_name_2 + predictor_variable_name_3</code> for as many predictor variables as we would like to add. Nothing else about the <code>lm</code> function changes.</p>
<p>We can interpret the results as follows:</p>
<ul>
<li><p>When comparing two groups who differ by one unit on their response to <code>perceived_useful</code>, but who have the same response to <code>perceived_ease_use</code>, the average response to <code>behavioral_intetions</code> for the group with the higher response to <code>perceived_useful</code> will be 0.2 units higher than the group with the lower response.</p></li>
<li><p>When comparing two groups who differ by one unit on their response to <code>perceived_ease_use</code>, but who have the same response to <code>perceived_useful</code>, the average response to <code>behavioral_intetions</code> for the group with the higher response to <code>perceived_ease_of_use</code> will be 0.28 units higher than the group with the lower response.</p></li>
</ul>
<p>We could also say: While controlling for <code>perceived_ease_use</code>, for every one unit increase in an individual’s perceptions of how useful the AI tool is (<code>perceived_useful</code>), we will see their intentions to use the AI tool increase by 0.2.</p>
<p>The <code>R-squared</code> value in our model is 0.2045388, which means that 20% of the variance in <code>behavioral_intention</code> can be explained by <code>perceived_useful</code> and <code>perceived_ease_use</code> together.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>